/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecryptRouteImport } from './routes/decrypt'
import { Route as EncryptRouteImport } from './routes/encrypt'
import { Route as SecurityRouteImport } from './routes/security'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecryptRoute = DecryptRouteImport.update({
  id: '/decrypt',
  path: '/decrypt',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptRoute = EncryptRouteImport.update({
  id: '/encrypt',
  path: '/encrypt',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decrypt': typeof DecryptRoute
  '/encrypt': typeof EncryptRoute
  '/security': typeof SecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decrypt': typeof DecryptRoute
  '/encrypt': typeof EncryptRoute
  '/security': typeof SecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decrypt': typeof DecryptRoute
  '/encrypt': typeof EncryptRoute
  '/security': typeof SecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decrypt' | '/encrypt' | '/security'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decrypt' | '/encrypt' | '/security'
  id: '__root__' | '/' | '/decrypt' | '/encrypt' | '/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecryptRoute: typeof DecryptRoute
  EncryptRoute: typeof EncryptRoute
  SecurityRoute: typeof SecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decrypt': {
      id: '/decrypt'
      path: '/decrypt'
      fullPath: '/decrypt'
      preLoaderRoute: typeof DecryptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encrypt': {
      id: '/encrypt'
      path: '/encrypt'
      fullPath: '/encrypt'
      preLoaderRoute: typeof EncryptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecryptRoute: DecryptRoute,
  EncryptRoute: EncryptRoute,
  SecurityRoute: SecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
